package com.pizzaserver.domain.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

/**
 * JPA Repository table columns definition
 * <p>Password is SHA1 hash generated by client-side</p>
 * <p>Token is used to verify if user has logged in</p>
 */
@Entity
@Table(name = "products_combined")
public class Product implements Serializable {


    @Id
    @Column(name = "id")
    private String id;

    @Column(name = "type")
    private String type;

    @Column(name = "name")
    private String name;

    @Column(name = "description")
    private String description;

    @Column(name = "costS")
    private String costS;

    @Column(name = "costM")
    private String costM;

    @Column(name = "costL")
    private String costL;

    @Column(name = "costU")
    private String costU;


    public Product(){

    }

    private Product(Builder builder) {
        id=builder.id;
        type=builder.type;
        name=builder.name;
        description=builder.description;
        costS=builder.costS;
        costM=builder.costM;
        costL=builder.costL;
        costU=builder.costU;
    }

    public String getId() {
        return id;
    }

    public String getType() {
        return type;
    }

    public String getName(){return name;}

    public String getDescription() {
        return description;
    }

    public String getCostS() {
        return costS;
    }

    public String getCostM() {
        return costM;
    }

    public String getCostL() {
        return costL;
    }

    public String getCostU() {
        return costU;
    }

    public String getCostBySize(String size){
        Map<String, String> map = new HashMap<>();
        map.put("S",costS);
        map.put("M",costM);
        map.put("L",costL);
        map.put("U",costU);
        return map.get(size).replace(',','.');
    }

    public static final class Builder {
        private String id;
        private String type;
        private String name;
        private String description;
        private String costS;
        private String costM;
        private String costL;
        private String costU;

        public Builder() {
        }

        public static Builder aProduct() {
            return new Builder();
        }

        public Builder withId(String id) {
            this.id = id;
            return this;
        }

        public Builder withType(String type) {
            this.type = type;
            return this;
        }

        public Builder withName(String name) {
            this.name = name;
            return this;
        }

        public Builder description(String description) {
            this.description = description;
            return this;
        }

        public Builder withCostS(String costS) {
            this.costS = costS;
            return this;
        }

        public Builder withCostM(String costM) {
            this.costM = costM;
            return this;
        }

        public Builder withCostL(String costL) {
            this.costL = costL;
            return this;
        }

        public Builder withCostU(String costU) {
            this.costU = costU;
            return this;
        }

        public Product build() {
            Product product = new Product();
            product.id = this.id;
            product.name = this.name;
            product.costU = this.costU;
            product.costL = this.costL;
            product.description = this.description;
            product.costS = this.costS;
            product.type = this.type;
            product.costM = this.costM;
            return product;
        }
    }

    /*public static final class Builder {
        private String id;
        private String type;
        private String description;
        private String costS;
        private String costM;
        private String costL;
        private String costU;

        public Builder() {
        }

        public Builder login(String login) {
            this.login = login;
            return this;
        }

        public Builder password(String password) {
            this.password = password;
            return this;
        }

        public Builder token(String token) {
            this.token = token;
            return this;
        }

        public ProductCSV build() {
            return new ProductCSV(this);
        }
    }*/

}
