package com.pizzaserver.domain.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

/**
 * JPA Repository table columns definition
 * <p>Password is SHA1 hash generated by client-side</p>
 * <p>Token is used to verify if user has logged in</p>
 */
@Entity
@Table(name = "products_combined")
public class Product implements Serializable {


    @Id
    @Column(name = "id")
    private Integer id;

    @Column(name = "type")
    private Integer type;

    @Column(name = "name")
    private String name;

    @Column(name = "description")
    private String description;

    @Column(name = "costS")
    private Float costS;

    @Column(name = "costM")
    private Float costM;

    @Column(name = "costL")
    private Float costL;

    @Column(name = "costU")
    private Float costU;


    public Product(){

    }

    private Product(Builder builder) {
        id=builder.id;
        type=builder.type;
        name=builder.name;
        description=builder.description;
        costS=builder.costS;
        costM=builder.costM;
        costL=builder.costL;
        costU=builder.costU;
    }


    public Integer getId() {
        return id;
    }

    public Integer getType() {
        return type;
    }

    public String getName(){return name;}

    public String getDescription() {
        return description;
    }

    public Float getCostS() {
        return costS;
    }

    public Float getCostM() {
        return costM;
    }

    public Float getCostL() {
        return costL;
    }

    public Float getCostU() {
        return costU;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Float getCostBySize(String size){
        Map<String, Float> map = new HashMap<>();
        map.put("S",costS);
        map.put("M",costM);
        map.put("L",costL);
        map.put("U",costU);
        return map.get(size);
    }

    public static final class Builder {
        private Integer id;
        private Integer type;
        private String name;
        private String description;
        private Float costS;
        private Float costM;
        private Float costL;
        private Float costU;

        public Builder() {
        }

        public static Builder aProduct() {
            return new Builder();
        }

        public Builder withId(int id) {
            this.id = id;
            return this;
        }

        public Builder withType(int type) {
            this.type = type;
            return this;
        }

        public Builder withName(String name) {
            this.name = name;
            return this;
        }

        public Builder description(String description) {
            this.description = description;
            return this;
        }

        public Builder withCostS(Float costS) {
            this.costS = costS;
            return this;
        }

        public Builder withCostM(Float costM) {
            this.costM = costM;
            return this;
        }

        public Builder withCostL(Float costL) {
            this.costL = costL;
            return this;
        }

        public Builder withCostU(Float costU) {
            this.costU = costU;
            return this;
        }

        public Product build() {
            Product product = new Product();
            product.id = this.id;
            product.name = this.name;
            product.costU = this.costU;
            product.costL = this.costL;
            product.description = this.description;
            product.costS = this.costS;
            product.type = this.type;
            product.costM = this.costM;
            return product;
        }
    }

    @Override
    public String toString() {
        return
                "id=" + id +
                ", type=" + type +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", costS='" + costS + '\'' +
                ", costM='" + costM + '\'' +
                ", costL='" + costL + '\'' +
                ", costU='" + costU+"";
    }

}
