package com.pizzaserver.domain.dto;

/**
 * Class used to store login data
 * <p>
 * Password is SHA1 hash generated by client-side
 */
public class UserLoginDto {

    private String login;
    private String password;

    public UserLoginDto(String login, String password) {
        this.login = login;
        this.password = password;
    }

    public UserLoginDto(Builder builder) {
        this.login = builder.login;
        this.password = builder.password;
    }

    public String getLogin() {
        return login;
    }

    public String getPassword() {
        return password;
    }


    public static final class Builder {
        private String login;
        private String password;

        private Builder() {
        }

        public static Builder anUserLoginDto() {
            return new Builder();
        }

        public Builder login(String login) {
            this.login = login;
            return this;
        }

        public Builder password(String password) {
            this.password = password;
            return this;
        }

        public UserLoginDto build() {
            return new UserLoginDto(this);
        }
    }
}
