package com.pizzaserver.domain.dto;

/**
 * Stores parameters for creating user
 * <p>
 * Password is SHA1 hash generated by client-side
 */
public class UserRegisterDto {

    private String login;
    private String password; //sha-1 hash

    public UserRegisterDto(String login, String password) {
        this.login = login;
        this.password = password;
    }

    public UserRegisterDto(Builder builder) {
        this.login = builder.login;
        this.password = builder.password;
    }

    public String getLogin() {
        return login;
    }

    public String getPassword() {
        return password;
    }


    public static final class Builder {
        private String login;
        private String password; //sha-1 hash

        private Builder() {
        }

        public static Builder anUserRegisterDto() {
            return new Builder();
        }

        public Builder login(String login) {
            this.login = login;
            return this;
        }

        public Builder password(String password) {
            this.password = password;
            return this;
        }

        public UserRegisterDto build() {
            return new UserRegisterDto(this);
        }
    }
}
